name: Angular Tests with FirefoxHeadless

on: [push, pull_request]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 'lts/*'

         - name: Print Firefox version
           run: firefox --version

         - name: Install dependencies
           run: npm install

         - name: Build
           run: npm run build

         - name: Test with FirefoxHeadless
           run: npm run test:ci
